<script type="text/javascript" src="<?php echo $this->bootstrapJS ?>"></script>
<link rel="stylesheet" href="<?php echo $this->bootstrapCSS ?>" />

<style>
    .clearfix:after {
        content: ".";
        display: block;
        clear: both;
        visibility: hidden;
        line-height: 0;
        height: 0;
    }

    html,body{height: 100.1%}
    body{background-color: #7F7F7F!important}

    #lw_fe_inputelement_lw_formular_template{width: 800px;height: 600px;}
    #tabs ul li a{color: #fff;}

    .activeline {background: #e8f2ff !important;}

    .active{background-color: #777;}

    .description {
        margin-bottom:5px;
        border:1px solid #aaa;
        border-radius: 5px;
        background-color:#eee;
        padding:10px;
    }

    .description h1{
        font-size: 20px;
        font-style: italic;
        margin-bottom: 15px;
    }

    .description p{margin-bottom: 10px;}

    .description #info{
        border: 1px solid red;
        padding: 10px 0 10px 300px;
        font-size: 16px;
        background-color: darkred;
        color: #fff;
    }

    legend.lwadminform {
        height: 20px;
        margin-bottom: 2px;
        line-height: 20px;
        width: 71px;
    }
    html body div#lwContent div {
        font-size: 12px!important;
    }

    fieldset.lwadminform {
        position: relative;
    }


    html body div#lwLeftnavi div#lwPageTreeNav.lwBoxLeftContent center form#gotoform input#gotoid {
        width: 45px;
        margin-bottom: 0;
    }
    html body div#lwLeftnavi div#lwPageTreeNav.lwBoxLeftContent center {
        height: 35px;
    }    


    #container{
        background-color: #fff;
        border: 1px solid #bbb;
        border-radius: 10px;
        padding: 10px;
        padding-bottom: 80px;
    }

    #container_form{margin-top: 20px;}

    .input-append input.span2 {height: 30px;width: 200px;margin-right: -3px;}
    .input-append button, .input-append button:hover {font-size: 20px; font-weight: bold; }

    a.tableLink{
        display:block;
        background-color: transparent;
        color: #333;
    }

    a.tableLink:hover{text-decoration: none;}
    a.iconpadding{padding: 5px;}

    #breadcrumb{margin-bottom: 10px;}

    #breadcrumb ul{
        margin: 0;
        padding: 0;
        list-style: none;
    }

    #breadcrumb a{
        background-color: transparent;
        color: #333;
    }

    #breadcrumb a:hover{text-decoration: none;background-color: #F5F5F5}

    #breadcrumb ul li{padding: 0;margin: 0;float: left;}

    #bottomRemove{
        border:1px solid #ddd;
        width: 36px;
        float: right; 
        text-align: center;
        padding: 5px;
        border-bottom-right-radius: 5px;
        border-bottom-left-radius: 5px;
        border-top: none;
    }
    #topRemove{
        border:1px solid #ddd;
        width: 36px;
        float: right; 
        text-align: center;
        padding: 5px;
        border-top-right-radius: 5px;
        border-top-left-radius: 5px;
        border-bottom: none;
    }

    input.cb_delete{margin-left: 7px;}


    .thumbnail{
        position: absolute;
        display: none;
        z-index: 5;
        background-color: #fff;
        border: 2px solid #666;
        max-width: 200px;
        min-height: 35px;
    }

    .edge{
        position: absolute;
        display: none;
        z-index: 1;
        width: 30px;
        height: 30px;
        -moz-transform:rotate(45deg);  
        -webkit-transform:rotate(45deg);  
        -o-transform:rotate(45deg);  
        -ms-transform:rotate(45deg);  
        background-color: #666;

    }
</style>

<script>
    $(document).ready(function() {
        $('th input:checkbox').click(function(e) {
            var table = $(e.target).parents('table:first');
            $('td input:checkbox', table).attr('checked', e.target.checked);
        });


        <?php if ($this->dir != "base" && !empty($this->dirContent)) : ?>
            <?php $i = 0; foreach($this->dirContent as $name => $info): ?>
                <?php if ($info["type"] == "picture"): ?>
                    var newTop = $("#href_thumbnail_<?php echo $i; ?>").position().top - 2;
                    var newLeft = $("#href_thumbnail_<?php echo $i; ?>").width();
                    $('#thumbnail_<?php echo $i; ?>').css({"position":"absolute", "top": newTop + "px", "left": (newLeft + 20) + "px"});
                    $('#edge_nr_<?php echo $i; ?>').css({"position":"absolute", "top": (newTop + 10) + "px", "left": (newLeft + 15) + "px"});

                    $('#href_thumbnail_<?php echo $i; ?>').mouseover(function() {
                        $('#thumbnail_<?php echo $i; ?>').show();
                        $('#edge_nr_<?php echo $i; ?>').show();
                    }).mouseout(function() {
                        $('#thumbnail_<?php echo $i; ?>').hide();
                        $('#edge_nr_<?php echo $i; ?>').hide();
                    });
                <?php endif; ?>
            <?php $i++; endforeach; ?>
        <?php endif; ?>
    
        <?php if($this->error): ?>
            <?php if(array_key_exists("ext", $this->error)): ?>
                alert("Sie haben versucht eine Datei vom Datentyp '<?php echo $this->error["ext"] ?>' hochzuladen. Dieser Datentyp ist nicht erlaubt.");
        <?php endif;endif; ?>
    
    });
</script>

<fieldset class="lwadminform">
    <legend class="lwadminform">LayoutFiles</legend>

    <div id="container">
        <div id="container_form">
            <?php if ($this->dir != "base"): ?>
                <form id="uploadFileForm" class="form-horizontal" action="<?php echo $this->baseUrl . "&dir=" . $this->dir . "&cmd=addFile"; ?>" method="POST" ENCTYPE="multipart/form-data">
                    <div class="clearfix">
                        <div class="control-group" style="float:left;padding-bottom: 0;margin-bottom: 0;">
                            <label class="control-label" for="newFile">Neue Datei</label>
                            <div class="controls">
                                <input id="newFile" name="newFile" type="file"><br>
                            </div>
                        </div>
                        <button style="margin-left:10px;float: left;" class="btn btn-primary" type="button" onclick="
                            var fileName = $('#newFile').val();
                            fileName = fileName.replace('C:\\fakepath\\', ''); 
                            fileName = fileName.replace(/[^A-Z.a-z0-9_-]/g, ''); 
                            $.ajax({
                                  url: '<?php echo $this->baseUrl; ?>&check=file',
                                  type: 'post',
                                  data: {'filename' : fileName, 'dir' : '<?php echo $this->dir; ?>'},
                                  success: function(data){
                                                if(data === 'NotAllowedExtension'){
                                                    alert('Sie haben versucht eine Datei hochzuladen, deren Datentyp nicht erlaubt ist.\nErlaubte Dateiendungen : jpg, jpeg, gif, png, bmp, css, js, htm, html, flv');
                                                }   
                                                else if(data === 'FilenameExisting'){
                                                    if(confirm('Es ist bereits eine Datei mit dem Namen : \''+fileName+'\' vorhanden. Soll diese &uuml;berschrieben werden ? ')) {$('form#uploadFileForm').submit();};
                                                }   
                                                else{
                                                    $('form#uploadFileForm').submit();
                                                }
                                        }
                                }); 
                                
                                ">speichern</button>
                    </div>
                </form>
            <?php else: ?>
                <form class="form-horizontal" action="<?php echo $this->baseUrl . "&dir=base&cmd=addDir"; ?>" method="POST">
                    <div class="control-group">
                        <label class="control-label" for="newdir">Neues Verzeichnis</label>
                        <div class="controls">
                            <div class="input-append">
                                <input class="span2" id="newdir" name="newDir" type="text">
                                <button class="btn btn-primary" type="submit">+</button>
                            </div>
                        </div>
                    </div>
                </form>
            <?php endif; ?>
        </div>
        <hr>
        <?php if ($this->dir != "base"): ?>
            <div id="breadcrumb" class="clearfix">
                <ul>
                    <li><a href="<?php echo $this->baseUrl . "&dir=base"; ?>"><i class="icon-folder-open"></i>&nbsp;Hauptverzeichnis LayoutFiles/</a></li>
                    <li><a href="<?php echo $this->baseUrl . "&dir=" . $this->dir; ?>"><i class="icon-folder-open"></i>&nbsp;<?php echo $this->dir; ?>/</a></li>
                </ul>
            </div>
            <div class="clearfix">
                <?php if (!empty($this->dirContent)): ?>
                    <form  id="deleteFilesFrom" action="<?php echo $this->baseUrl . "&dir=".$this->dir."&cmd=deleteFiles"; ?>" method="POST">
                        <input type="hidden" name="dir" value="<?php echo $this->dir; ?>">
                        <div class="clearfix">
                            <div id="topRemove">
                                <a class="tablelink" href="#" onclick="if(confirm('Ausgew&auml;hlte Elemente l&ouml;schen ?')) {$('form#deleteFilesFrom').submit();};" ><i class="icon-remove"></i></a>
                            </div>
                        </div>
                        <table class="table table-hover table-bordered" style="margin-bottom:0;border-bottom-right-radius: 0;border-top-right-radius: 0;">
                            <thead>
                                <tr>
                                    <th style="min-width: 150px;">Name</th>
                                    <th>Datum</th>
                                    <th>Gr&ouml;&szlig;e</th>
                                    <th>Url</th>
                                    <th style="width: 30px;" >&nbsp;</th>
                                    <th style="width: 30px;" ><input class="cb_delete" type="checkbox"></th>
                                </tr>
                            </thead>

                            <tbody>
                                <?php $i = 0;foreach ($this->dirContent as $name => $info):?>
                                    <tr>
                                        <?php if ($info["type"] == "picture"): ?>
                                            <td id="href_thumbnail_<?php echo $i; ?>" class="imgage">
                                                <a  class="tablelink" href="#"><i class="icon-picture"></i>&nbsp;<?php echo $name; ?></a>
                                                <div  class="thumbnail" id="thumbnail_<?php echo $i; ?>">
                                                    <img border="0" src="<?php echo str_replace($name, "thumbnail_".$name, $info["url"]); ?>">
                                                </div>
                                                <div id="edge_nr_<?php echo $i; ?>" class="edge">&nbsp;</div>
                                            </td>
                                        <?php else: ?>
                                            <td><a class="tableLink" href="#"><i class="icon-file"></i>&nbsp;<?php echo $name; ?></a></td>
                                        <?php endif; ?>

                                        <td><?php echo $info["date"]; ?></td>
                                        <td><?php echo $info["size"]; ?></td>
                                        <td><?php echo $info["url"]; ?></td>
                                        <td><a class="tableLink" href="#" onclick="if(confirm('Element \' <?php echo $name; ?> \' wirklich umbennen ?\nDies wird die Url zu dieser Datei ver&auml;ndern !\nSollte die Datei bereits auf Seiten eingebunden sein, muss die Url dort angepasst werden.')) {
                                            var newName = prompt('Bitte geben Sie den neuen Namen ein:','<?php $explodedName = explode(".", $name); echo $explodedName[0]; ?>');
                                            if (newName !== null){
                                                newName = newName.replace(/[^A-Za-z0-9_-]/g, '');  
                                                self.location.href = '<?php echo $this->baseUrl . "&dir=".$this->dir."&cmd=renameFile&from=" . urlencode($name) ."&to=" ?>' + newName + '<?php $explodedName = explode(".", $name); echo ".".$explodedName[1]; ?>';
                                            }
                                        };" ><i class="icon-pencil"></i>&nbsp;</a></td>

                                        <td><input class="cb_delete" type="checkbox" name="delete[<?php echo $name; ?>]" value="1" ></td>

                                    </tr>
                                    <?php $i++; ?>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <div id="bottomRemove">
                            <a class="tablelink" href="#" onclick="if(confirm('Ausgew&auml;hlte Elemente l&ouml;schen ?')) {$('form#deleteFilesFrom').submit();};" ><i class="icon-remove"></i></a>
                        </div>
                    </form>
                <?php else: ?>
                    <p>keine Dateien vorhanden.</p>
            <?php endif; ?>
            </div>
            <?php else: ?>
                <div id="breadcrumb" class="clearfix" style="margin-bottom: 36px;">
                    <ul>
                        <li><a href="<?php echo $this->baseUrl . "&dir=base"; ?>"><i class="icon-folder-open"></i>&nbsp;Hauptverzeichnis LayoutFiles/</a></li>
                    </ul>
                </div>
                <?php if (!empty($this->dirContent)): ?>
                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Dateien</th>
                                <th>Gr&ouml;&szlig;e</th>
                                <th style="width: 30px;" >&nbsp;</th>
                                <th style="width: 30px;" >&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                    <?php foreach ($this->dirContent as $name => $info): ?>
                            <tr>
                                <td><a class="tableLink" href="<?php echo $this->baseUrl . "&dir=" . $name; ?>"><i class="icon-folder-close"></i>&nbsp;<?php echo $name; ?></a></td>
                                <td><?php echo $info["fileCount"]; ?></td>
                                <td><?php echo $info["completeFileSize"]; ?></td>
                                
                                <td><a class="tableLink" href="#" onclick="if(confirm('Verzeichnis \' <?php echo $name; ?> \' wirklich umbennen ?\nDies wird die Url zu diesem Verzeichnis und allen enthaltenden Dateien ver&auml;ndern !\nSollten die Dateien bereits auf Seiten eingebunden sein, m&uuml;ssen dort alle Urls angepasst werden.')) {
                                    var newName = prompt('Bitte geben Sie den neuen Namen ein:','<?php echo $name; ?>');
                                    if (newName !== null){
                                        newName = newName.replace(/[^A-Za-z0-9_-]/g, '');  
                                        self.location.href = '<?php echo $this->baseUrl . "&cmd=renameDir&from=" . urlencode($name) ."&to=" ?>' + newName;
                                    }
                                };" ><i class="icon-pencil"></i>&nbsp;</a></td>
                                
                                <?php if ($info["fileCount"] == 0): ?>
                                    <td><a class="tableLink iconpadding" href="<?php echo $this->baseUrl . "&cmd=deleteDir&dir=" . $name; ?>" onclick="return confirm('Das Verzeichnis \' <?php echo $name; ?> \' wirklich l&ouml;schen ?');"><i class="icon-remove"></i></a></td>
                                <?php else: ?>
                                    <td>&nbsp;</td>
                                <?php endif; ?>
                            </tr>
                    <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <p>keine Verzeichnisse vorhanden.</p>
                <?php endif; ?>
            <?php endif; ?>

    </div>

</fieldset>